#define __SC_ptrace_may_access  0
#define __SC_ptrace_traceme  1
#define __SC_capget  2
#define __SC_capset  3
#define __SC_capable  4
#define __SC_real_capable  5
#define __SC_real_capable_noaudit  6
#define __SC_acct  7
#define __SC_sysctl  8
#define __SC_quotactl  9
#define __SC_quota_on  10
#define __SC_syslog  11
#define __SC_settime  12
#define __SC_vm_enough_memory  13
#define __SC_vm_enough_memory_mm  14
#define __SC_vm_enough_memory_kern  15
#define __SC_bprm_set_creds  16
#define __SC_bprm_check  17
#define __SC_bprm_committing_creds  18
#define __SC_bprm_committed_creds  19
#define __SC_bprm_secureexec  20
#define __SC_sb_alloc  21
#define __SC_sb_free  22
#define __SC_sb_copy_data  23
#define __SC_sb_kern_mount  24
#define __SC_sb_show_options  25
#define __SC_sb_statfs  26
#define __SC_sb_mount  27
#define __SC_sb_check_sb  28
#define __SC_sb_umount  29
#define __SC_sb_umount_close  30
#define __SC_sb_umount_busy  31
#define __SC_sb_post_remount  32
#define __SC_sb_post_addmount  33
#define __SC_sb_pivotroot  34
#define __SC_sb_post_pivotroot  35
#define __SC_sb_set_mnt_opts  36
#define __SC_sb_clone_mnt_opts  37
#define __SC_sb_parse_opts_str  38
#define __SC_inode_alloc  39
#define __SC_inode_free  40
#define __SC_inode_init_security  41
#define __SC_path_mknod  42
#define __SC_path_mkdir  43
#define __SC_path_rmdir  44
#define __SC_path_unlink  45
#define __SC_path_symlink  46
#define __SC_path_link  47
#define __SC_path_rename  48
#define __SC_path_truncate  49
#define __SC_inode_create  50
#define __SC_inode_link  51
#define __SC_inode_unlink  52
#define __SC_inode_symlink  53
#define __SC_inode_mkdir  54
#define __SC_inode_rmdir  55
#define __SC_inode_mknod  56
#define __SC_inode_rename  57
#define __SC_inode_readlink  58
#define __SC_inode_follow_link  59
#define __SC_inode_permission  60
#define __SC_inode_setattr  61
#define __SC_inode_getattr  62
#define __SC_inode_delete  63
#define __SC_inode_setxattr  64
#define __SC_inode_post_setxattr  65
#define __SC_inode_getxattr  66
#define __SC_inode_listxattr  67
#define __SC_inode_removexattr  68
#define __SC_inode_need_killpriv  69
#define __SC_inode_killpriv  70
#define __SC_inode_getsecurity  71
#define __SC_inode_setsecurity  72
#define __SC_inode_listsecurity  73
#define __SC_inode_getsecid  74
#define __SC_file_permission  75
#define __SC_file_alloc  76
#define __SC_file_free  77
#define __SC_file_ioctl  78
#define __SC_file_mmap  79
#define __SC_file_mprotect  80
#define __SC_file_lock  81
#define __SC_file_fcntl  82
#define __SC_file_set_fowner  83
#define __SC_file_send_sigiotask  84
#define __SC_file_receive  85
#define __SC_dentry_open  86
#define __SC_task_create  87
#define __SC_cred_free  88
#define __SC_prepare_creds  89
#define __SC_commit_creds  90
#define __SC_kernel_act_as  91
#define __SC_kernel_create_files_as  92
#define __SC_task_setuid  93
#define __SC_task_fix_setuid  94
#define __SC_task_setgid  95
#define __SC_task_setpgid  96
#define __SC_task_getpgid  97
#define __SC_task_getsid  98
#define __SC_task_getsecid  99
#define __SC_task_setgroups  100
#define __SC_task_setnice  101
#define __SC_task_setioprio  102
#define __SC_task_getioprio  103
#define __SC_task_setrlimit  104
#define __SC_task_setscheduler  105
#define __SC_task_getscheduler  106
#define __SC_task_movememory  107
#define __SC_task_kill  108
#define __SC_task_wait  109
#define __SC_task_prctl  110
#define __SC_task_to_inode  111
#define __SC_ipc_permission  112
#define __SC_ipc_getsecid  113
#define __SC_msg_msg_alloc  114
#define __SC_msg_msg_free  115
#define __SC_msg_queue_alloc  116
#define __SC_msg_queue_free  117
#define __SC_msg_queue_associate  118
#define __SC_msg_queue_msgctl  119
#define __SC_msg_queue_msgsnd  120
#define __SC_msg_queue_msgrcv  121
#define __SC_shm_alloc  122
#define __SC_shm_free  123
#define __SC_shm_associate  124
#define __SC_shm_shmctl  125
#define __SC_shm_shmat  126
#define __SC_sem_alloc  127
#define __SC_sem_free  128
#define __SC_sem_associate  129
#define __SC_sem_semctl  130
#define __SC_sem_semop  131
#define __SC_d_instantiate  132
#define __SC_getprocattr  133
#define __SC_setprocattr  134
#define __SC_netlink_send  135
#define __SC_netlink_recv  136
#define __SC_secid_to_secctx  137
#define __SC_secctx_to_secid  138
#define __SC_release_secctx  139
#define __SC_unix_stream_connect  140
#define __SC_unix_may_send  141
#define __SC_socket_create  142
#define __SC_socket_post_create  143
#define __SC_socket_bind  144
#define __SC_socket_connect  145
#define __SC_socket_listen  146
#define __SC_socket_accept  147
#define __SC_socket_sendmsg  148
#define __SC_socket_recvmsg  149
#define __SC_socket_getsockname  150
#define __SC_socket_getpeername  151
#define __SC_socket_getsockopt  152
#define __SC_socket_setsockopt  153
#define __SC_socket_shutdown  154
#define __SC_sock_rcv_skb  155
#define __SC_socket_getpeersec_stream  156
#define __SC_socket_getpeersec_dgram  157
#define __SC_sk_alloc  158
#define __SC_sk_free  159
#define __SC_sk_clone  160
#define __SC_sk_classify_flow  161
#define __SC_req_classify_flow  162
#define __SC_sock_graft  163
#define __SC_inet_conn_request  164
#define __SC_inet_csk_clone  165
#define __SC_inet_conn_established  166
#define __SC_xfrm_policy_alloc  167
#define __SC_xfrm_policy_clone  168
#define __SC_xfrm_policy_free  169
#define __SC_xfrm_policy_delete  170
#define __SC_xfrm_state_alloc  171
#define __SC_xfrm_state_alloc_acquire  172
#define __SC_xfrm_state_delete  173
#define __SC_xfrm_state_free  174
#define __SC_xfrm_policy_lookup  175
#define __SC_xfrm_state_pol_flow_match  176
#define __SC_xfrm_decode_session  177
#define __SC_skb_classify_flow  178
#define __SC_key_alloc  179
#define __SC_key_free  180
#define __SC_key_permission  181
#define __SC_key_getsecurity  182
#define __SC_audit_rule_init  183
#define __SC_audit_rule_known  184
#define __SC_audit_rule_free  185
#define __SC_audit_rule_match  186
