#define __SC_ptrace_may_access  0
#define __SC_ptrace_traceme  1
#define __SC_capget  2
#define __SC_capset  3
#define __SC_capable  4
#define __SC_acct  5
#define __SC_sysctl  6
#define __SC_quotactl  7
#define __SC_quota_on  8
#define __SC_syslog  9
#define __SC_settime  10
#define __SC_vm_enough_memory  11
#define __SC_bprm_set_creds  12
#define __SC_bprm_check_security  13
#define __SC_bprm_secureexec  14
#define __SC_bprm_committing_creds  15
#define __SC_bprm_committed_creds  16
#define __SC_sb_alloc_security  17
#define __SC_sb_free_security  18
#define __SC_sb_copy_data  19
#define __SC_sb_kern_mount  20
#define __SC_sb_show_options  21
#define __SC_sb_statfs  22
#define __SC_sb_mount  23
#define __SC_sb_check_sb  24
#define __SC_sb_umount  25
#define __SC_sb_umount_close  26
#define __SC_sb_umount_busy  27
#define __SC_sb_post_remount  28
#define __SC_sb_post_addmount  29
#define __SC_sb_pivotroot  30
#define __SC_sb_post_pivotroot  31
#define __SC_sb_set_mnt_opts  32
#define __SC_sb_clone_mnt_opts  33
#define __SC_sb_parse_opts_str  34
#define __SC_path_unlink  35
#define __SC_path_mkdir  36
#define __SC_path_rmdir  37
#define __SC_path_mknod  38
#define __SC_path_truncate  39
#define __SC_path_symlink  40
#define __SC_path_link  41
#define __SC_path_rename  42
#define __SC_inode_alloc_security  43
#define __SC_inode_free_security  44
#define __SC_inode_init_security  45
#define __SC_inode_create  46
#define __SC_inode_link  47
#define __SC_inode_unlink  48
#define __SC_inode_symlink  49
#define __SC_inode_mkdir  50
#define __SC_inode_rmdir  51
#define __SC_inode_mknod  52
#define __SC_inode_rename  53
#define __SC_inode_readlink  54
#define __SC_inode_follow_link  55
#define __SC_inode_permission  56
#define __SC_inode_setattr  57
#define __SC_inode_getattr  58
#define __SC_inode_delete  59
#define __SC_inode_setxattr  60
#define __SC_inode_post_setxattr  61
#define __SC_inode_getxattr  62
#define __SC_inode_listxattr  63
#define __SC_inode_removexattr  64
#define __SC_inode_need_killpriv  65
#define __SC_inode_killpriv  66
#define __SC_inode_getsecurity  67
#define __SC_inode_setsecurity  68
#define __SC_inode_listsecurity  69
#define __SC_inode_getsecid  70
#define __SC_file_permission  71
#define __SC_file_alloc_security  72
#define __SC_file_free_security  73
#define __SC_file_ioctl  74
#define __SC_file_mmap  75
#define __SC_file_mprotect  76
#define __SC_file_lock  77
#define __SC_file_fcntl  78
#define __SC_file_set_fowner  79
#define __SC_file_send_sigiotask  80
#define __SC_file_receive  81
#define __SC_dentry_open  82
#define __SC_task_create  83
#define __SC_cred_free  84
#define __SC_cred_prepare  85
#define __SC_cred_commit  86
#define __SC_kernel_act_as  87
#define __SC_kernel_create_files_as  88
#define __SC_task_setuid  89
#define __SC_task_fix_setuid  90
#define __SC_task_setgid  91
#define __SC_task_setpgid  92
#define __SC_task_getpgid  93
#define __SC_task_getsid  94
#define __SC_task_getsecid  95
#define __SC_task_setgroups  96
#define __SC_task_setnice  97
#define __SC_task_setioprio  98
#define __SC_task_getioprio  99
#define __SC_task_setrlimit  100
#define __SC_task_setscheduler  101
#define __SC_task_getscheduler  102
#define __SC_task_movememory  103
#define __SC_task_kill  104
#define __SC_task_wait  105
#define __SC_task_prctl  106
#define __SC_task_to_inode  107
#define __SC_ipc_permission  108
#define __SC_ipc_getsecid  109
#define __SC_msg_msg_alloc_security  110
#define __SC_msg_msg_free_security  111
#define __SC_msg_queue_alloc_security  112
#define __SC_msg_queue_free_security  113
#define __SC_msg_queue_associate  114
#define __SC_msg_queue_msgctl  115
#define __SC_msg_queue_msgsnd  116
#define __SC_msg_queue_msgrcv  117
#define __SC_shm_alloc_security  118
#define __SC_shm_free_security  119
#define __SC_shm_associate  120
#define __SC_shm_shmctl  121
#define __SC_shm_shmat  122
#define __SC_sem_alloc_security  123
#define __SC_sem_free_security  124
#define __SC_sem_associate  125
#define __SC_sem_semctl  126
#define __SC_sem_semop  127
#define __SC_netlink_send  128
#define __SC_netlink_recv  129
#define __SC_d_instantiate  130
#define __SC_getprocattr  131
#define __SC_setprocattr  132
#define __SC_secid_to_secctx  133
#define __SC_secctx_to_secid  134
#define __SC_release_secctx  135
#define __SC_unix_stream_connect  136
#define __SC_unix_may_send  137
#define __SC_socket_create  138
#define __SC_socket_post_create  139
#define __SC_socket_bind  140
#define __SC_socket_connect  141
#define __SC_socket_listen  142
#define __SC_socket_accept  143
#define __SC_socket_sendmsg  144
#define __SC_socket_recvmsg  145
#define __SC_socket_getsockname  146
#define __SC_socket_getpeername  147
#define __SC_socket_getsockopt  148
#define __SC_socket_setsockopt  149
#define __SC_socket_shutdown  150
#define __SC_socket_sock_rcv_skb  151
#define __SC_socket_getpeersec_stream  152
#define __SC_socket_getpeersec_dgram  153
#define __SC_sk_alloc_security  154
#define __SC_sk_free_security  155
#define __SC_sk_clone_security  156
#define __SC_sk_getsecid  157
#define __SC_sock_graft  158
#define __SC_inet_conn_request  159
#define __SC_inet_csk_clone  160
#define __SC_inet_conn_established  161
#define __SC_req_classify_flow  162
#define __SC_xfrm_policy_alloc_security  163
#define __SC_xfrm_policy_clone_security  164
#define __SC_xfrm_policy_free_security  165
#define __SC_xfrm_policy_delete_security  166
#define __SC_xfrm_state_alloc_security  167
#define __SC_xfrm_state_free_security  168
#define __SC_xfrm_state_delete_security  169
#define __SC_xfrm_policy_lookup  170
#define __SC_xfrm_state_pol_flow_match  171
#define __SC_xfrm_decode_session  172
#define __SC_key_alloc  173
#define __SC_key_free  174
#define __SC_key_permission  175
#define __SC_key_getsecurity  176
#define __SC_audit_rule_init  177
#define __SC_audit_rule_known  178
#define __SC_audit_rule_match  179
#define __SC_audit_rule_free  180
