#define __KA_ptrace	0
#define __KA_capget	1
#define __KA_capset_check	2
#define __KA_capset_set	3
#define __KA_capable	4
#define __KA_acct	5
#define __KA_sysctl	6
#define __KA_quotactl	7
#define __KA_quota_on	8
#define __KA_syslog	9
#define __KA_settime	10
#define __KA_vm_enough_memory	11
#define __KA_bprm_alloc_security	12
#define __KA_bprm_free_security	13
#define __KA_bprm_apply_creds	14
#define __KA_bprm_post_apply_creds	15
#define __KA_bprm_set_security	16
#define __KA_bprm_check_security	17
#define __KA_bprm_secureexec	18
#define __KA_sb_alloc_security	19
#define __KA_sb_free_security	20
#define __KA_sb_copy_data	21
#define __KA_sb_kern_mount	22
#define __KA_sb_statfs	23
#define __KA_sb_mount	24
#define __KA_sb_check_sb	25
#define __KA_sb_umount	26
#define __KA_sb_umount_close	27
#define __KA_sb_umount_busy	28
#define __KA_sb_post_remount	29
#define __KA_sb_post_mountroot	30
#define __KA_sb_post_addmount	31
#define __KA_sb_pivotroot	32
#define __KA_sb_post_pivotroot	33
#define __KA_inode_alloc_security	34
#define __KA_inode_free_security	35
#define __KA_inode_init_security	36
#define __KA_inode_create	37
#define __KA_inode_link	38
#define __KA_inode_unlink	39
#define __KA_inode_symlink	40
#define __KA_inode_mkdir	41
#define __KA_inode_rmdir	42
#define __KA_inode_mknod	43
#define __KA_inode_rename	44
#define __KA_inode_readlink	45
#define __KA_inode_follow_link	46
#define __KA_inode_permission	47
#define __KA_inode_setattr	48
#define __KA_inode_getattr	49
#define __KA_inode_delete	50
#define __KA_inode_setxattr	51
#define __KA_inode_post_setxattr	52
#define __KA_inode_getxattr	53
#define __KA_inode_listxattr	54
#define __KA_inode_removexattr	55
#define __KA_inode_need_killpriv	56
#define __KA_inode_killpriv	57
#define __KA_inode_getsecurity	58
#define __KA_inode_setsecurity	59
#define __KA_inode_listsecurity	60
#define __KA_file_permission	61
#define __KA_file_alloc_security	62
#define __KA_file_free_security	63
#define __KA_file_ioctl	64
#define __KA_file_mmap	65
#define __KA_file_mprotect	66
#define __KA_file_lock	67
#define __KA_file_fcntl	68
#define __KA_file_set_fowner	69
#define __KA_file_send_sigiotask	70
#define __KA_file_receive	71
#define __KA_dentry_open	72
#define __KA_task_create	73
#define __KA_task_alloc_security	74
#define __KA_task_free_security	75
#define __KA_task_setuid	76
#define __KA_task_post_setuid	77
#define __KA_task_setgid	78
#define __KA_task_setpgid	79
#define __KA_task_getpgid	80
#define __KA_task_getsid	81
#define __KA_task_getsecid	82
#define __KA_task_setgroups	83
#define __KA_task_setnice	84
#define __KA_task_setioprio	85
#define __KA_task_getioprio	86
#define __KA_task_setrlimit	87
#define __KA_task_setscheduler	88
#define __KA_task_getscheduler	89
#define __KA_task_movememory	90
#define __KA_task_kill	91
#define __KA_task_wait	92
#define __KA_task_prctl	93
#define __KA_task_reparent_to_init	94
#define __KA_task_to_inode	95
#define __KA_ipc_permission	96
#define __KA_msg_msg_alloc_security	97
#define __KA_msg_msg_free_security	98
#define __KA_msg_queue_alloc_security	99
#define __KA_msg_queue_free_security	100
#define __KA_msg_queue_associate	101
#define __KA_msg_queue_msgctl	102
#define __KA_msg_queue_msgsnd	103
#define __KA_msg_queue_msgrcv	104
#define __KA_shm_alloc_security	105
#define __KA_shm_free_security	106
#define __KA_shm_associate	107
#define __KA_shm_shmctl	108
#define __KA_shm_shmat	109
#define __KA_sem_alloc_security	110
#define __KA_sem_free_security	111
#define __KA_sem_associate	112
#define __KA_sem_semctl	113
#define __KA_sem_semop	114
#define __KA_netlink_send	115
#define __KA_netlink_recv	116
/* allow module stacking */
#define __KA_register_security	117
#define __KA_d_instantiate	118
#define __KA_getprocattr	119
#define __KA_setprocattr	120
#define __KA_secid_to_secctx	121
#define __KA_release_secctx	122
#ifdef CONFIG_SECURITY_NETWORK
#define __KA_unix_stream_connect	123
#define __KA_unix_may_send	124
#define __KA_socket_create	125
#define __KA_socket_post_create	126
#define __KA_socket_bind	127
#define __KA_socket_connect	128
#define __KA_socket_listen	129
#define __KA_socket_accept	130
#define __KA_socket_post_accept	131
#define __KA_socket_sendmsg	132
#define __KA_socket_recvmsg	133
#define __KA_socket_getsockname	134
#define __KA_socket_getpeername	135
#define __KA_socket_getsockopt	136
#define __KA_socket_setsockopt	137
#define __KA_socket_shutdown	138
#define __KA_socket_sock_rcv_skb	139
#define __KA_socket_getpeersec_stream	140
#define __KA_socket_getpeersec_dgram	141
#define __KA_sk_alloc_security	142
#define __KA_sk_free_security	143
#define __KA_sk_clone_security	144
#define __KA_sk_getsecid	145
#define __KA_sock_graft	146
#define __KA_inet_conn_request	147
#define __KA_inet_csk_clone	148
#define __KA_inet_conn_established	149
#define __KA_req_classify_flow	150
#endif/* CONFIG_SECURITY_NETWORK */
#ifdef CONFIG_SECURITY_NETWORK_XFRM
#define __KA_xfrm_policy_alloc_security	151
#define __KA_xfrm_policy_clone_security	152
#define __KA_xfrm_policy_free_security	153
#define __KA_xfrm_policy_delete_security	154
#define __KA_xfrm_state_alloc_security	155
#define __KA_xfrm_state_free_security	156
#define __KA_xfrm_state_delete_security	157
#define __KA_xfrm_policy_lookup	158
#define __KA_xfrm_state_pol_flow_match	159
#define __KA_xfrm_decode_session	160
#endif/* CONFIG_SECURITY_NETWORK_XFRM */
/* key management security hooks */
#ifdef CONFIG_KEYS
#define __KA_key_alloc	161
#define __KA_key_free	162
#define __KA_key_permission	163
#endif/* CONFIG_KEYS */
